### ISSUE TITLE
Heroku integration fails

### ISSUE THREAD

**Issue by BjarturHafthors** [SD4RK/epicstore_api#1]
Hi there @SD4RK !

I've been trying to set up a program that uses this API on Heroku and when installing the API on there, the installation fails with the following message:

```
Collecting epicstore-api==0.0.3
         Downloading epicstore_api-0.0.3.tar.gz (8.8 kB)
           ERROR: Command errored out with exit status 1:
            command: /app/.heroku/python/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-mgjkj0gi/epicstore-api/setup.py'"'"'; __file__='"'"'/tmp/pip-install-mgjkj0gi/epicstore-api/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-mgjkj0gi/epicstore-api/pip-egg-info
                cwd: /tmp/pip-install-mgjkj0gi/epicstore-api/
           Complete output (9 lines):
           Traceback (most recent call last):
             File "<string>", line 1, in <module>
             File "/tmp/pip-install-mgjkj0gi/epicstore-api/setup.py", line 2, in <module>
               from epicstore_api import __version__ as version, __author__ as author
             File "/tmp/pip-install-mgjkj0gi/epicstore-api/epicstore_api/__init__.py", line 14, in <module>
               from .api import *
             File "/tmp/pip-install-mgjkj0gi/epicstore-api/epicstore_api/api.py", line 29, in <module>
               import requests
           ModuleNotFoundError: No module named 'requests'
```

Everything works fine when I install it locally, and I have tried pre-installing requests on Heroku as well, which yields the same result.

Can you think of any possible cause and/or solution to this?

Cheers!

**Comment by SD4RK** [comment]
Hello. As far as I know, when you're trying to install a library on heroku or on any other hosting you have to write bash command like that:
`pip3 install epicstore_api --user`
This will avoid environmental constraints.

**Comment by BjarturHafthors** [comment]
I've been using a requirements.txt, where I simply list all the requirements in the following format for each of the included packages:

`epicstore-api==0.0.3`

This was recommended by Heroku and works for all other packages included in my project.

Pip installs all the packages with the specified version for each package listed in the requirements file.

**Comment by SD4RK** [comment]
Well, other cause of this can be that you have both `Pipfile` and `requirements.txt`.

If it is, you have to remove `Pipfile` and you should be fine. The library does not support a Pipfile at the moment.

**Comment by BjarturHafthors** [comment]
I am not using a Pipfile, so that should not be the issue.

**Comment by SD4RK** [comment]
Could you send your Python version? Let's see if the issue is related with that.

**Comment by BjarturHafthors** [comment]
I am currently running Python version 3.6.8

**Comment by SD4RK** [comment]
For me all works fine. I can't reproduce your issue. But it looks like an environmental constraints. The issue isn't related to the library, so sorry, but you should about a solution by yourself.

**Comment by DearFuture1** [comment]
I'm having the exact same issue right now with my heroku bot. Already tried everything :(
