### ISSUE TITLE
No price information

### ISSUE THREAD

**Issue by GagikProger** [SD4RK/epicstore_api#10]
Hi. How can I get the price of the game? Beacuse when I use code from examples, there is no price in json. Here is the code.
```
from epicstore_api import EpicGamesStoreAPI
import json


def main():
    """
    Print all games in filter range
    """
    api = EpicGamesStoreAPI()
    games = api.fetch_store_games(
        product_type='games/edition/base|bundles/games',
        count=10,
        with_price=True
    )
    print('API Response:\n', json.dumps(games, indent=4))


if __name__ == '__main__':
    main()
```

**Comment by SD4RK** [comment]
Use `api.fetch_catalog` if you want to get the game's price.

**Comment by GagikProger** [comment]
I did like you said and there are only 275 games but I wrote count=1000 as parameter. Are there any limits?

**Comment by GagikProger** [comment]
Maybe there is a method that can give me a price by name of the game. I can`t find about it in your docs.

**Comment by SD4RK** [comment]
Huh, the bug when `fetch_store_games` does not return price even with `with_price=True` was an internal one. Fixed this, you can now use it again (look commit https://github.com/SD4RK/epicstore_api/commit/affabd96e5515d21d1bd82ad83a297f1f82fdbed). `fetch_catalog` does not return all the games.

**Comment by GagikProger** [comment]
Oh, thank you very much. I will try tomorrow.
