### ISSUE TITLE
game image = none?

### ISSUE THREAD

**Issue by Rekutor** [SD4RK/epicstore_api#13]
In free_games_example.py Line 16. Type Thumbnail didnt exist so game_thumbnail = None. The Heck?

**Comment by Rekutor** [comment]
I fixed it with this:
```for image in game['keyImages']:
       if image['type'] == 'DieselStoreFrontWide':
           game_thumbnail = image['url']
           game_thumbnail = "%20".join( game_thumbnail.split() )

There were blank spaces in the string and that fucked up shit.

**Comment by SD4RK** [comment]
I guess it is the API not url-encoding the URL. The library does not provide any pre-processing of the given data, it tries to return the original response as it is only doing some validation (and that pretty much was the point). So it is fine and won't fix for me.
