### ISSUE TITLE
Deals

### ISSUE THREAD

**Issue by ingmferrer** [SD4RK/epicstore_api#2]
Hello,

It is possible to get current deals with game name and thumbnail with this library?

Thanks.

**Comment by SD4RK** [comment]
Hello,

I'm not sure if I got you right, so do you want to get all the games from "Free Games" section? This function does not exist in the library at the moment, but I've found a request that fetches that games, so I think I will add it.

**Comment by SD4RK** [comment]
I've added a function, take a look at this example: https://github.com/SD4RK/epicstore_api/blob/master/examples/free_games_example.py

**Comment by ingmferrer** [comment]
Alright, I will test it in the next weekend. I plan to list all free games in a web app that I'm doing so users can check if there are free goodies.

**Comment by ingmferrer** [comment]
Excellent. It works as expected. Thank you.
