### ISSUE TITLE
Offer ID missing in product data of example code

### ISSUE THREAD

**Issue by PureFallen** [SD4RK/epicstore_api#23]
Upon attempting to run the example code provided in the README file, it became evident that the Offer ID is no longer included within the Product Data Request with `get_product`.

```py
from epicstore_api import EpicGamesStoreAPI, OfferData

if __name__ == '__main__':
    api = EpicGamesStoreAPI()

    # Fortnite
    namespace, slug = list(api.get_product_mapping().items())[0]
    first_product = api.get_product(slug)

    offers = []
    for page in first_product['pages']:
        if page.get('offer') is not None:
            offers.append(OfferData(page['namespace'], page['offer']['id']))

    print(offers)
```

Expected Behavior: It prints out the OfferData Object containing the tuple of namespace and Offer ID.
Actual Behavior: `KeyError 'id'` is thrown in `offers.append(...)`.

I did dig around within the page, but the ID that once used to be inside `page['offer']` is nowhere to be found. `id_` seems to be unrelated.

When attempting to reproduce this behavior with another product I was unable to achieve the same error. For example:

```py
from epicstore_api import EpicGamesStoreAPI, OfferData

if __name__ == '__main__':
    api = EpicGamesStoreAPI()

    first_product = api.get_product('phantasy-star-online-2')

    offers = []
    for page in first_product['pages']:
        if page.get('offer') is not None:
            offers.append(OfferData(page['namespace'], page['offer']['id']))

    print(offers)
```

```
> [OfferData(namespace='bf333e6236914222a95a536389c05813', offer_id='f6fb771bec434d1082cc419b9b4b8bfb')]
```

I am uncertain on what causes this issue, but it might be something related to the product itself.

**Comment by SD4RK** [comment]
That's weird but some offers don't seem to have an ID attached to them. And as the library is not strongly typed and would just return you the original response as is, it caused the example to crash out when such an example was found.

Fixed the example to account for such possibility in the latest commit. Closed.
