### ISSUE TITLE
Fetching product data for games without a slug listed on product mapping

### ISSUE THREAD

**Issue by 648trindade** [SD4RK/epicstore_api#29]
Hi!

I'm trying to create a script to automatize the creation of custom categories for my games on Heroic Games Launcher. I'm trying to use this API. By acessing the product data dictionary, I can retrieve the game genres/categories from a "tags" field (which is pretty strangely formatted)

I've noticed that a lot of games have not an entry on product mapping (retrieved with `epicstore_api.EpicGamesStoreAPI.get_product_mapping`) (e.g. the game [Filament](https://store.epicgames.com/pt-BR/p/filament-332a92))

I have the namespace id for the game (such info is present on heroic internal data, but I can also retrive it from searching into store games fetched via API), however I can't find a slug on products mapping.

If I try to use some obvious slugs (e.g. `filament`, `filament-332a92` - from store page URL) it don't work: the `get_product` method fails. Is it a bug on mapping? If not, how do I do it?

**Comment by woctezuma** [comment]
Just leaving this here, I don't know if a piece of info on this page could help:
- https://egdata.app/offers/296453e71c884f95aecf4d582cf66915/items

**Comment by 648trindade** [comment]
Okay, I've managed a way to do it.

The Heroic launcher configuration files had the namespace id, so by combining the results from `get_store_games` and `get_collection_tags`, I could retrieve the tags for almost my entire collection
