### ISSUE TITLE
Offers Query Is No Longer Gets Price Information [Solution]

### ISSUE THREAD

**Issue by slymn08183** [SD4RK/epicstore_api#4]
"catalogQuery" That you used as "OFFERS_QUERY" is no longer valid. You have to change it with new one in order to get price information of the games. But when you chage it you need to add a new variable to your post body called "includeSubItems". Here its the an e.g. 

variables_ = {
                    'locale': self.locale,
                    'country': self.country,
                    'includeSubItems': False
                }

The Query that I used:

"\n	query catalogQuery($productNamespace: String!, $offerId: String!, $locale: String, $country: String!, $includeSubItems: Boolean!) {\n  Catalog {\n    catalogOffer(namespace: $productNamespace, id: $offerId, locale: $locale) {\n      title\n      id\n      namespace\n      description\n      effectiveDate\n      expiryDate\n      isCodeRedemptionOnly\n      keyImages {\n        type\n        url\n      }\n      seller {\n        id\n        name\n      }\n      productSlug\n      urlSlug\n      url\n      tags {\n        id\n      }\n      items {\n        id\n        namespace\n      }\n      customAttributes {\n        key\n        value\n      }\n      categories {\n        path\n      }\n      price(country: $country) {\n        totalPrice {\n          discountPrice\n          originalPrice\n          voucherDiscount\n          discount\n          currencyCode\n          currencyInfo {\n            decimals\n          }\n          fmtPrice(locale: $locale) {\n            originalPrice\n            discountPrice\n            intermediatePrice\n          }\n        }\n        lineOffers {\n          appliedRules {\n            id\n            endDate\n            discountSetting {\n              discountType\n            }\n          }\n        }\n      }\n    }\n    offerSubItems(namespace: $productNamespace, id: $offerId) @include(if: $includeSubItems) {\n      namespace\n      id\n      releaseInfo {\n        appId\n        platform\n      }\n    }\n  }\n}\n"

**Comment by SD4RK** [comment]
Hello, thanks for the information, the query was changed, yeah, I'll look into it soon. 

But for the future reference, queries' arguments shouldn't be put in `variables_`, instead it should be put in `_make_graphql_query` kwargs, or, in the multiple_query_variables' dicts.

**Comment by slymn08183** [comment]
Thanks, I'll look again my codes.
