### ISSUE TITLE
Release 0.1.2 with the latest changes

### ISSUE THREAD

**Issue by george-lim** [SD4RK/epicstore_api#9]
Hi there,

Do you mind making a release with the recent changes in master? The latest changes allow your module to be installed properly in other projects, so it is a critical change. I'm waiting for the release so that I can push my projects that depend on epicstore_api.

**Comment by SD4RK** [comment]
Hello,

I'm making a new 1.0.0 version with some of the client stuff and auth functions. So I'll release it with all the minor stuff as soon as the client part will be done.

**Comment by SD4RK** [comment]
Hello, done, wanted to release that changes with a new 1.0.0 version with some client stuff, but I actually don't mind to make a minor release now.

**Comment by george-lim** [comment]
Oh I see, yeah thanks so much!
